config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :airports
  resources :flights
  resources :bookings

  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name:'Flight', foreign_key: 'departure_id',inverse_of: :departure_airport
    has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_id', inverse_of: :arrival_airport

    validates :code, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    has_many :passengers, inverse_of: :booking
    belongs_to :flight, inverse_of: :bookings

    accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :departure_airport, class_name: 'Airport', foreign_key: 'departure_id',inverse_of: :departing_flights
    belongs_to :arrival_airport, class_name:'Airport', foreign_key: 'arrival_id',inverse_of: :arriving_flights
    has_many :bookings, inverse_of: :flight
    has_many :passengers, through: :bookings

    def self.user_search(search_params)
        where(departure_id: search_params[:departure_id],
               arrival_id: search_params[:arrival_id],
               departure_time: search_params[:departure_time]
            )
    end

    def date_formatted
        departure_time.strftime("%d/%m/%Y")
    end

end

app/models/passenger.rb
class Passenger < ApplicationRecord
    belongs_to :booking, inverse_of: :passengers
    has_many :flights, through: :bookings
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
    def new
        @airport=Airport.new 
    end

    def index 
        @airports=Airport.all 
    end

    def create 
        @airport=Airport.new(airport_params)
    end

    private 
    def airport_params 
        params.require(:airport).permit(:code)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def new
        @booking = Booking.new
        @flight = Flight.find(params[:flight_id])
        @booking.passengers.build ##This is necessary for the passengers form to be created.
    end

    def create
        @flight = Flight.find(booking_params[:flight_id])
        @booking =@flight.bookings.build(booking_params)

        if @booking.save
            PassengerMailer.with(booking_id: @booking.id).confirmation_email.deliver_now
            redirect_to @booking
        else
            render new
        end
    end

    def index
        @bookings=Booking.all
    end

    def show
        @booking=Booking.find(params[:id])
    end

    private



    def booking_params
        params.require(:booking).permit(:passengers,:flight_id,passengers_attributes: [:name,:passenger_id, :email])
    end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
    def index
        ##collections
        @departures=Flight.all.map{|f|[f.departure_airport.code,f.departure_airport.id]}.sort{|a,b| a<=>b}.uniq
        @arrivals=Flight.all.map{|f|[f.arrival_airport.code,f.arrival_airport.id]}.sort{|a,b| a<=>b}.uniq
        @dates=Flight.all.pluck(:departure_time).sort{|a,b|a<=>b}.uniq
        ##----


        ##

        @search_results=Flight.user_search(search_params)
        
        
        @flights=Flight.all

    end

    def new
        @flight=Flight.new
    end

    def show
               
        @flight=Flight.find(params[:id])
    end

    def create 
        @flight=Flight.new(flight_params)
        if save
            redirect_to root_path
        else
            render new
        end
    end



    private
    def search_params
        params.permit(:departure_id,:arrival_id,:departure_time,:duration,:airline,:flight_number,:passenger_number,:commit)
    end

    def flight_params 
        params.require(:flight).permit([:id,:departure_id,:arrival_id,:duration,:departure_time,:flight_number])
    end
end

##Schema stuff


##create_table "flights", force: :cascade do |t|
  ##  t.integer "departure_id"
    ##t.integer "arrival_id"
    ##t.datetime "departure_time"
    ##t.datetime "duration"
    ##t.string "airline"
    ##t.integer "flight_number"
    ##t.datetime "created_at", null: false
    ##t.datetime "updated_at", null: false
    ##t.integer "passenger_number"
  ##end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController

    def new
        @passenger= Passenger.new 
    end

    def create
        @passenger=Passenger.new(passenger_params)

        if save
            redirect_to root_path  
        else
            render new
        end
    end

    private

    def passenger_params
        params.require(:passenger).permit(:email,:name,:id)
    end

end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/_booking_form.html.erb
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being created:</h2>
      <ul>
        <% @booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
    </div>
<%end%>

<h5><strong>Flight Info:</strong></h5>
<ul>
<li>From: <%=@flight.departure_airport.code%></li>
<li>To: <%=@flight.arrival_airport.code%></li>
<li>Passengers: <%=@flight.passenger_number%></li>
<li>Departure: <%=@flight.date_formatted%></li>
</ul>
<%=form_with(model: @booking, url: bookings_path) do |f|%>
<h5>Flight ID: <%=@flight.id%></h5>
<%=f.hidden_field :flight_id, value: @flight.id%>
<h4>Passenger Info:</h4>
<%=f.fields_for :passengers do |sf|%>
<h5><%=sf.label :name%></h5>
    <%=sf.text_field :name%>
<h5><%=sf.label :email%></h5>
    <%=sf.text_field :email%>
    <%end%>
    <br>
<%=f.submit 'Create Flight Booking!'%>
</li>
</ul>
<%end%>

app/views/bookings/new.html.erb
<%= render 'booking_form'%>

app/views/bookings/show.html.erb
<h1>The booking with passengers and all that</h1>

<p>Booking ID: <%=@booking.id%></p> <br>
<%@pass=Passenger.where(booking_id:@booking.id)%> <br>
<%@pass.each do |pass|%> <br>
<%=pass.name%> <br>
<%=pass.email%> <br>
<%end%>
<%@bird=Flight.find(@booking.flight_id)%> <br>
<%=@bird.airline%> <br>
<%=@bird.date_formatted%> <br>


<br>
<%=link_to 'lets go HOME', root_path%>

app/views/flights/_container_flights.html.erb
<header><h1>Flight-Booker</h1></header>



<div> <h2>Container for the fligths</h2>

<div class="flight list">
<%sorted=@flights.sort{|a,b| a.departure_time <=> b.departure_time}%>
<ul>   <%sorted.each do |f|%>

<li>
    <%departure=Airport.find(f.departure_id)%>
    <%arraival=Airport.find(f.arrival_id)%>
    <%num=32 - f.passenger_number%>
<h6>Departing: <%=departure.code%></h6>
<h6>Destination: <%=arraival.code%></h6>
<h6>Date: <%=f.date_formatted%></h6>
<h6>Seats Available: <%=num > 0 ? num : 'No Vacancy'%></h6>

</li>

<%end%>
</ul>
</div>


</div>

app/views/flights/_results_flights.html.erb
<%if @search_results.present?%>
<%=form_with(model: @flight, url: new_booking_path, method: :get) do |form|%>

    
    <h3>Search Results</h3>

        <%@search_results.each do |fly|%>
    <ul>
    <li>
    <%num=32-fly.passenger_number%>
    <%no_vac='NO VACANCY FOR YOU IN THIS FLIGHT!'%>
    <%message="Available seats : #{num}"%>
        <%="Flight id: #{fly.id}"%>
        <%=fly.departure_airport.code%>
        <%=fly.arrival_airport.code%>
        <%=fly.date_formatted%>
        <%=num > 0 ? message : no_vac %>

        <%=form.radio_button :flight_id, fly.id%>

        <%end%>

    <%=form.submit "Book Flight"%>
    </li>
    </ul>
<%end%>
<%else%>
<h3><%='Please search a flight!' %></h3>
<%end%>

app/views/flights/_search_flights.html.erb
<h2>Search for a flight!</h2>

<%=form_with(url: flights_path, method: :get) do |f|%>


<h5>Departures: <%=f.select(:departure_id,options_for_select(@departures), selected: params[:departure_id])%></h5>
<h5>Arrivals:  <%=f.select(:arrival_id,options_for_select(@arrivals), selected: params[:arrival_id])%></h5>
<h5>Date:  <%=f.select(:departure_time,options_for_select(@dates), selected: params[:departure_time])%></h5>
<h5>Number of seats:  <%=f.select(:passenger_number,(1..4), selected: params[:passenger_number])%></h5>

<%=f.submit 'Search'%>

<%end%>

app/views/flights/_search_results.html.erb
<h4>Search results</h4> <br>


<ul>
        <%@search_results.each do |f|%>



<li> <%departure=Airport.find(f.departure_id)%>
    <%arraival=Airport.find(f.arrival_id)%>
    <%num=32 - f.passenger_number%>
<h6>Departing: <%=departure.code%></h6>
<h6>Destination: <%=arraival.code%></h6>
<h6>Date: <%=f.departure_time.strftime("%d/%m/%Y")%></h6>
<h6>Seats Available: <%=num > 0 ? num : 'No Vacancy'%></h6>
</li>
<%end%>
</ul>

app/views/flights/index.html.erb
<div> 

<%=render 'search_flights'%>
</div> <br>

<div><%=render 'results_flights'%></div>

<div> <%=render 'container_flights'%></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>